name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnet-version: ["6.0.x", "7.0.x", "8.0.x", "9.0.x"]
        framework: ["net6.0", "net7.0", "net8.0", "net9.0"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build with dotnet
        run: dotnet build src/Relewise.Client.Extensions/ --configuration Debug --framework ${{ matrix.framework }}
        
      - name: Unit testing
        run: dotnet test
