name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { dotnet-version: "6.0.x", framework: "net6.0" }
          - { dotnet-version: "7.0.x", framework: "net7.0" }
          - { dotnet-version: "8.0.x", framework: "net8.0" }
          - { dotnet-version: "9.0.x", framework: "net9.0" }
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.config.dotnet-version }}
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{ matrix.config.dotnet-version }}
          
      - name: List installed SDKs
        run: dotnet --list-sdks

      - name: Use .NET CLI Version ${{ matrix.config.dotnet-version }}
        run: dotnet --version        

      - name: Build with dotnet
        run: dotnet build src/Relewise.Client.Extensions/ --configuration Debug --framework ${{ matrix.config.framework }}
        
      - name: Unit testing
        run: dotnet test
